# Usage of config file.
#
# ipset:
#     <a unique name of category>:
#         ipset-name: <the ipset name>
#         list: [<array of a url addresses>]
#         file: <path to the file with ip addresses (your own list) - value is optional>
#     .
#     .
#     .
# ipset-temp: <name of temporary ipset>
# verbose: <boolean>

ipset:
    # drop all
    blacklist-total:
        ipset-name: blacklist
        list:
            - "http://www.spamhaus.org/drop/drop.txt"
            - "http://www.spamhaus.org/drop/drop.txt"
            - "http://www.spamhaus.org/drop/edrop.txt"
            - "http://lists.blocklist.de/lists/all.txt"
            - "http://danger.rulez.sk/projects/bruteforceblocker/blist.php"
            - "https://www.turris.cz/greylist-data/greylist-latest.csv"
        file:
            - "/opt/my-blacklist.txt"

    # allow only specific port
    blacklist-port:
        ipset-name: blacklist-port
        list:
            - "http://www.ipdeny.com/ipblocks/data/countries/cn.zone"
            - "http://www.ipdeny.com/ipblocks/data/countries/tr.zone"
        file:

    # allow all
    whitelist:
        ipset-name: whitelist
        list:
            - "http://www.ipdeny.com/ipblocks/data/countries/cz.zone"
            - "http://www.ipdeny.com/ipblocks/data/countries/sk.zone"
        file:

# name of temp ipset
ipset-temp: tempxlist

# Verbose output, True or False
verbose: True
